title: Jonathan Nyachoti
email: jonathanmogaka90@gmail.com
description: >-
  Portfolio of an IT Support Professional and Cybersecurity Enthusiast.
  Passionate about solving real-world tech problems through support,
  automation, and security.

twitter_username: jonathannyachoti
github_username: jmnyachoti
minimal_mistakes_skin: neon
search: true

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Africa/Nairobi

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Jonathan Nyachoti"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "IT Support Specialist | Cybersecurity Learner | CCNA Certified | Bridging people and technology."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/jonathan-mogaka"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jmnyachoti"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:jonathanmogaka90@gmail.com"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/jonathan-mogaka"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jmnyachoti"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:jonathanmogaka90@gmail.com"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
